### ISSUE TITLE
[FEAT] 네이게이션 바 구현

### ISSUE THREAD

**Issue by seunghoria** [seunghoria/Mae1U#4]
## 💡 Issue
네비게이션 바 영역을 구현합니다.

## 📝  Todo
- [ ] 나의 증명서, 상대방 인증하기, 더보기
- [x] Text "본인인증 수단이 추가되었습니다."
- [ ] 버튼 _ blue
- [ ] 본인인증 하기 버튼 터치 이후, Text "코로나 19 예방접종 내역" 변경
