### ISSUE TITLE
[FEAT] 카드 앞면 _ 본인인증 증명서 구현

### ISSUE THREAD

**Issue by seunghoria** [seunghoria/Mae1U#5]
## 💡 Issue
카드 앞면 _ 본인인증 증명서를 구현합니다.

## 📝  Todo
- [x] 배경 _ Gray Rectangle
- [x] Text 본인인증 증명서
- [x] 하단 _ overlay white Rectangle
- [x] 본인인증 하기 버튼
- [x] 본인인증 하기 버튼 터치 이후, 카드 뒷면 변경
