### ISSUE TITLE
[FEAT] 버튼 클릭 시 변경 구현

### ISSUE THREAD

**Issue by seunghoria** [seunghoria/Mae1U#6]
## 💡 Issue
버튼 클릭시 네비게이션바 텍스트와
카드 뒷면의 텍스트, 색상으로 변경합니다.

## 📝  Todo
- [ ] 배경 _ Blue Rectangle
- [ ] Text 코로나 19 예방접종 증명서
- [ ] 하단 _ overlay white Rectangle
- [ ] Text 접종차수 1차, 백신 제조사 화이자
